name: gpt_issue_checker
description: 'Use gpt to check issues'
author: wgh136

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: blue

# Define your inputs here.
inputs:
  model:
    description: The model to use
    required: false
  prompt:
    description: The prompt to use
    required: false
  api-url:
    description: The API URL. Defaults to openai.com
    required: false
  api-key:
    description: The API key
    required: true
  github-token:
    description: The GitHub token
    required: true

# Define your outputs here.
outputs:
  result:
    description: The result of the action

runs:
  using: node20
  main: dist/index.js
