name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  model:
    description: The model to use
    required: false
  prompt:
    description: The prompt to use
    required: false
  api-url:
    description: The API URL. Defaults to openai.com
    required: false
  api-key:
    description: The API key
    required: true
  github-token:
    description: The GitHub token
    required: true

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
