name: Check Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  check:
    name: Check Issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Use Local Action
        id: test-action
        uses: ./
        with:
          api-url: ${{ secrets.API_URL }}
          api-key: ${{ secrets.API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
